services:

  web:
  build: .

  env_file:
    - .env

  extra_hosts:
    - "host.docker.internal:host-gateway"

  environment:
    REDIS_URL: redis://redis:6379/0

  depends_on:
    redis:
      condition: service_healthy

  volumes:
    - static_volume:/app/staticfiles

  expose:
    - "8000"

  restart: unless-stopped

  redis:

    image: redis:7-alpine

    container_name: chatapp_redis

    command:
      redis-server --appendonly yes

    volumes:
      - redis_data:/data

    healthcheck:

      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]

      interval: 5s

      timeout: 3s

      retries: 10

    restart: unless-stopped



volumes:

  static_volume:

  postgres_data:

  redis_data: