services:

  web:
    image: ghcr.io/cnafateh/chatapp:latest

    container_name: chatapp

    env_file:
      - .env

    volumes:
      - chatapp_static:/app/staticfiles

    depends_on:
      redis:
        condition: service_healthy

    expose:
      - "8000"

    restart: unless-stopped

    networks:
      - database
      - proxy
      - chatapp_internal


  redis:
    image: redis:7-alpine

    container_name: chatapp-redis

    command:
      redis-server --appendonly yes

    volumes:
      - chatapp_redis:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

    restart: unless-stopped

    networks:
      - chatapp_internal


volumes:

  chatapp_static:

  chatapp_redis:


networks:

  database:
    external: true

  proxy:
    external: true

  chatapp_internal:
    driver: bridge