# Generated by Django 6.0.5 on 2026-10-05 13:22

import chat.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_member_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='public_id',
            field=models.UUIDField(null=True, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='privatechat',
            name='public_id',
            field=models.UUIDField(null=True, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('avatar', models.FileField(blank=True, upload_to=chat.models.avatar_path)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('show_phone', models.BooleanField(default=False)),
                ('use_gravatar', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
